### ISSUE TITLE
Offline trainer cause an error for me.

### ISSUE THREAD

**Issue by Fekedew** [Mquinn960/offline-trainer#13]
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.3) C:\build\3_4_winpack-bindings-win64-vc14-static\opencv\modules\ml\src\svm.cpp:2118: error: (-212:Parsing error) SVM model data is invalid, check sv_count, var_* and class_count tags in function 'cv::ml::SVMImpl::write'
]
	at org.opencv.core.Algorithm.save_0(Native Method)
	at org.opencv.core.Algorithm.save(Algorithm.java:78)
	at com.mquinn.trainer.sl_extensions.SvmService.finaliseSVMTraining(SvmService.java:100)
	at com.mquinn.trainer.ImageProcessor.finalise(ImageProcessor.java:55)
	at com.mquinn.trainer.ImageRunner.getFilesDeep(ImageRunner.java:57)
	at com.mquinn.trainer.Main.main(Main.java:94)

Process finished with exit code 1

**Comment by Mquinn960** [comment]
Hey,

Thanks for your issue - could you maybe give some supporting info here instead of simply posting your exception?

- What part of the documentation are you stuck on?
- What have you tried already?
- What were you trying to do when this happened?

This exception normally happens when your SVM model data isn't right, for example a malformed image, or not enough samples.

Matt

**Comment by Fekedew** [comment]
Thanks for getting back to me.

Ya may be my error is because of not enough sample i prepared only one
dataset for testing reason.

Let me talk you on telegram pls +251 948309006

With best regards
Fekedew Hailemariam
Software engineering student at wolkite university, Ethiopia.

**Comment by Fekedew** [comment]
> Hey,
> 
> Thanks for your issue - could you maybe give some supporting info here instead of simply posting your exception?
> 
> * What part of the documentation are you stuck on?
> * What have you tried already?
> * What were you trying to do when this happened?
> 
> This exception normally happens when your SVM model data isn't right, for example a malformed image, or not enough samples.
> 
> Matt
Enough sample means Matt, I use one dataset (80 image in train folder and 20 image in test folder) isn't enough?

**Comment by Mquinn960** [comment]
Hi @Fekedew - please keep discussion to github, this is an academic project and I do not offer support for it. 

I have written multiple guides for how to use this which others have followed successfully - please follow along with the guides and you should be able to put the pieces together.

If you have a specific issue please post it as an issue with details and myself or others may help you.

Matt
