### ISSUE TITLE
Error with ximgproc while running with /new libraries and .dll file, anyone can help?

### ISSUE THREAD

**Issue by msabri19m** [Mquinn960/offline-trainer#9]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.ximgproc.Ximgproc.thinning_0(JJI)V
	at org.opencv.ximgproc.Ximgproc.thinning_0(Native Method)
	at org.opencv.ximgproc.Ximgproc.thinning(Ximgproc.java:1227)
	at mquinn.sign_language.processing.SkeletonFrameProcessor.process(SkeletonFrameProcessor.java:24)
	at mquinn.sign_language.processing.MainFrameProcessor.process(MainFrameProcessor.java:19)
	at com.mquinn.trainer.ImageProcessor.process(ImageProcessor.java:38)
	at com.mquinn.trainer.ImageRunner.processFile(ImageRunner.java:92)
	at com.mquinn.trainer.ImageRunner.getFilesRecursive(ImageRunner.java:81)
	at com.mquinn.trainer.ImageRunner.getFilesDeep(ImageRunner.java:45)
	at com.mquinn.trainer.Main.main(Main.java:99)

**Comment by chengke96** [comment]
Some problem here

**Comment by Mquinn960** [comment]
Hey I might have a look at this at the weekend - this is to do with loading OpenCV binaries. You could try adding your own installation of OpenCV as a module library in the meantime.

**Comment by chengke96** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\User\Documents\GIT local\offline-trainer\new\opencv_java343.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.mquinn.trainer.Main.main(Main.java:11)

After several tried, I solved this problem by replacing the opencv_java343.dll from opencv to the one inside the \offline-trainer\new\opencv_java343.dll

**Comment by chengke96** [comment]
However, it ended up with this error:
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at com.mquinn.trainer.ImageRunner.getFilesDeep(ImageRunner.java:53)
	at com.mquinn.trainer.Main.main(Main.java:90)

**Comment by chengke96** [comment]
Exception in thread "main" java.lang.ArithmeticException: / by zero
at com.mquinn.trainer.ImageRunner.getFilesDeep(ImageRunner.java:53)
at com.mquinn.trainer.Main.main(Main.java:90)

Is it my data set input too less caused this error?

**Comment by Mquinn960** [comment]
Hey yes it's possible you're not bringing back any images in your input folder, try debugging to see if this is the case

**Comment by itsWaqasCh** [comment]
@chengke96 Where to replace that opencv_java343.dll file. I don't have any folder of open CV in my offline trainer. I am facing the similar issue.

**Comment by chengke96** [comment]
![image](https://user-images.githubusercontent.com/55948336/86356783-6e071000-bc9f-11ea-83bc-50b73c689473.png)

**Comment by Mquinn960** [comment]
Nice :). Please feel free to submit the lib changes on a clean branch pull request.

**Comment by chengke96** [comment]
> @chengke96 Where to replace that opencv_java343.dll file. I don't have any folder of open CV in my offline trainer. I am facing the similar issue.

It is worked for you now?

**Comment by chengke96** [comment]
@itsWaqasCh Is it worked for you now?

**Comment by itsWaqasCh** [comment]
Have you guys updated the "Offline Trainer" file? @Mquinn960 @chengke96

**Comment by itsWaqasCh** [comment]
And Can you please tell me how to configure IntelliJ for this file? @chengke96

**Comment by chengke96** [comment]
@itsWaqasCh I didn't do any configuration on this file, i just replaced the file "opencv_java343.dll" from opencv after installed the opencv343 to the one inside the \offline-trainer\new\opencv_java343.dll

**Comment by itsWaqasCh** [comment]
@chengke96 Can you please share the link to download OpenCV343.dll file?

**Comment by chengke96** [comment]
https://github.com/opencv/opencv/releases/tag/3.4.3
can try this

**Comment by itsWaqasCh** [comment]
@chengke96 I can't find .dll file on this link. Can you share the .dll file of openCV, Please? Here is my Gmail: waqasanwar947@gmail.com

**Comment by chengke96** [comment]
![image](https://user-images.githubusercontent.com/55948336/86613937-d712be80-bfe4-11ea-972f-7efb25c311bf.png)
you download and install it, then you will find the dll inside the file

**Comment by itsWaqasCh** [comment]
@chengke96 Hey Brother, Thanks a lot for your help. That issue was fixed. But now, I have come up with this error. 
![Screenshot (201)](https://user-images.githubusercontent.com/42888893/86618412-4e8b2280-bfd2-11ea-81d7-6cb5e31176cf.png)

**Comment by itsWaqasCh** [comment]
@chengke96 Have you find the solution of this one?

**Comment by chengke96** [comment]
![image](https://user-images.githubusercontent.com/55948336/87044436-13366100-c229-11ea-9f7b-74d9cf7b4b80.png)

Find your dataset file address and remember to put "\\" at behind

**Comment by Mquinn960** [comment]
Going to call this one fixed :) thanks @chengke96
